name: Build main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Patch Cauldron
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git submodule update --init --recursive
          ./cauldron jar

      - uses: actions/upload-artifact@v2
        with:
          name: Cauldron-JDK8
          path: Cauldron-paperclip.jar
